name: ibis_ui
description: Ibis is Website UI Toolkit with Dart, like Flutter, AngularDart, React.js, and Next.js etc.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

# dev_dependencies:
#   pedantic: ^1.10.0
#   test: ^1.16.0
